config.load_autoconfig()
config.bind("J", "tab-next")
config.bind("K", "tab-prev")
config.set("editor.command", ["kitty", "-e", "nvim", "{file}"])
config.set("colors.webpage.preferred_color_scheme", "dark")
config.bind(',m', 'spawn mpv {url}')
config.bind(',M', 'hint links spawn mpv {hint-url}')
